draw_sprite_ext(sMZeta_Cocoon0, -1, (x + ((piece0x + xoff0) * facing)), ((y + piece0y) + yoff0), facing, 1, (piece0a * facing), -1, 1)
draw_sprite_ext(sMZeta_Cocoon1, -1, (x + ((piece1x + xoff1) * facing)), ((y + piece1y) + yoff1), facing, 1, (piece1a * facing), -1, 1)
draw_sprite_ext(sMZeta_Cocoon2, -1, (x + ((piece2x + xoff2) * facing)), ((y + piece2y) + yoff2), facing, 1, (piece2a * facing), -1, 1)
draw_sprite_ext(sMZeta_Cocoon3, -1, (x + ((piece3x + xoff3) * facing)), ((y + piece3y) + yoff3), facing, 1, (piece3a * facing), -1, 1)
draw_sprite_ext(sMZeta_Cocoon4, -1, (x + ((piece4x + xoff4) * facing)), ((y + piece4y) + yoff4), facing, 1, (piece4a * facing), -1, 1)
draw_sprite_ext(sMZeta_Cocoon_Base, -1, x, y, facing, 1, 0, -1, 1)
