draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) + xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, 1)
draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) + xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, 1)
draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) - xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, 1)
draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) - xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, 1)
draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) + (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, 1)
draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) + (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, 1)
draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) - (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, 1)
draw_background_ext(bgA5Activation, floor(((((view_xview[0] * xratio) - (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, 1)
if (global.event[250] > 0)
{
    draw_set_blend_mode(bm_add)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) + xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, light_alpha)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) + xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, light_alpha)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) - xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, light_alpha)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) - xoffset) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, light_alpha)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) + (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, light_alpha)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) + (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, light_alpha)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) - (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, 1, 0, -1, light_alpha)
    draw_background_ext(bgA5ActivationLights, floor(((((view_xview[0] * xratio) - (xoffset * 2)) - (view_wview[0] / 2)) + 400)), floor(((view_yview[0] * yratio) + yoffset)), 1, -1, 0, -1, light_alpha)
    draw_set_blend_mode(bm_normal)
}
