event_inherited()
misc = get_text("ItemsMenu", "Misc")
morph = get_text("ItemsMenu", "MorphBall")
spider = get_text("ItemsMenu", "SpiderBall")
spring = get_text("ItemsMenu", "SpringBall")
bomb = get_text("ItemsMenu", "Bombs")
pgrip = get_text("ItemsMenu", "PowerGrip")
sattack = get_text("ItemsMenu", "ScrewAttack")
