canbeX = 0
CollisionBottom = 0
CollisionTop = 0
CollisionLeft = 0
CollisionRight = 0
i = 0
WallLeft = 368
gravity = 0
gravity_direction = 270
state = 0
statetime = 0
facing = 1
facingplayer = 0
turning = 0
myhealth = global.mod_torizohealthform1
if (global.difficulty >= 2)
    myhealth = global.mod_torizohealthform1hard
damage = global.mod_torizondamageform1
canbehit = 1
flashing = 0
fxtimer = 0
instance_create(0, 0, oTorizoWall)
myobj1 = instance_create(x, y, oTorizoBottom)
myobj1.damage = damage
stepdelay = 30
nextstepdelay = 30
walkspeed = 0.3
image_index_last = 0
proj_damage = 0
scan_log(34, get_text("ScanEvents", "ScanMechanism"), 180, 0)
dead = 0
