with (op[0])
    instance_destroy()
with (op[1])
    instance_destroy()
with (op[2])
    instance_destroy()
with (op[3])
    instance_destroy()
with (op[4])
    instance_destroy()
with (op[5])
    instance_destroy()
with (op[6])
    instance_destroy()
with (op[7])
    instance_destroy()
with (op[8])
    instance_destroy()
with (op[9])
    instance_destroy()
with (op[10])
    instance_destroy()
with (op[11])
    instance_destroy()
with (op[12])
    instance_destroy()
with (op[13])
    instance_destroy()
with (op[14])
    instance_destroy()
with (op[15])
    instance_destroy()
with (op[16])
    instance_destroy()
with (op[50])
    instance_destroy()
