canbeX = 0
wall_u = 90
wall_l = 90
wall_r = 230
wall_d = 870
next_attack = 0
image_angle = 0
target_angle = 0
rot_speed = 0
cam = instance_create(x, y, oObjectCamera)
cam.target_obj = id
s1 = instance_create(x, y, oTesterShield)
s2 = instance_create(x, y, oTesterShield)
s3 = instance_create(x, y, oTesterShield)
s4 = instance_create(x, y, oTesterShield)
soffset = 0
target_soff = 0
soffmax = 24
sangle = 0
starget_angle = 0
srot_speed = 5
sangle_timer = 0
shuriken = 0
enableforcefield = 0
change_time = 300
flashing = 0
attacks = 0
s1.image_angle = image_angle
s2.image_angle = (image_angle + 90)
s3.image_angle = (image_angle + 180)
s4.image_angle = (image_angle + 270)
c1 = instance_create(x, y, oTesterCannon)
c2 = instance_create(x, y, oTesterCannon)
c3 = instance_create(x, y, oTesterCannon)
c4 = instance_create(x, y, oTesterCannon)
coffset = 0
target_coff = 0
coffmax = 54
c1.image_angle = image_angle
c2.image_angle = (image_angle + 90)
c3.image_angle = (image_angle + 180)
c4.image_angle = (image_angle + 270)
eye = instance_create(x, y, oTesterEye)
glass = instance_create(x, y, oTesterGlass)
state = 0
statetime = 0
targetx = x
targety = y
movetotarget = 1
movespeed = 1
directrotate = 0
aim_x = 0
aim_y = 0
dead = 0
