with (oDrawMap2)
    instance_destroy()
with (oMapCursor)
    instance_destroy()
with (oSubscreenMenu)
    instance_destroy()
with (oSubScreenSuit)
    instance_destroy()
with (oSubScreenBeam)
    instance_destroy()
with (oSubScreenMisc)
    instance_destroy()
with (oSubScreenBoots)
    instance_destroy()
with (oSubScrPlayer)
    instance_destroy()
with (oLogScreenControl)
    instance_destroy()
with (oPauseMenuOptions)
    instance_destroy()
with (oOptionsMain)
    instance_destroy()
with (oOptionsDisplay)
    instance_destroy()
with (oOptionsSound)
    instance_destroy()
with (oOptionsControl)
    instance_destroy()
with (oOptionsKeyboard)
    instance_destroy()
with (oOptionsJoypad)
    instance_destroy()
with (oOptionsQuit)
    instance_destroy()
with (oOptionsReload)
    instance_destroy()
with (oOptionsExtras)
    instance_destroy()
with (oOptionsMod)
    instance_destroy()
