var omega_list, omega_type_sprites;
global.omega_types = ds_map_create()
omega_list = ds_list_create()
ds_list_add(omega_list, 332, 334, 336)
omega_type_sprites = ds_list_create()
ds_list_add(omega_type_sprites, 625, 1518, 1516)
ds_list_shuffle(omega_type_sprites)
for (i = 0; i < ds_list_size(omega_list); i += 1)
    ds_map_add(global.omega_types, ds_list_find_value(omega_list, i), ds_list_find_value(omega_type_sprites, i))
ds_map_add(global.omega_types, 314, 625)
ds_list_destroy(omega_list)
ds_list_destroy(omega_type_sprites)
