fx = instance_create(x, y, oMachine1Beam)
fx.rotdir = rotdir
fx = instance_create(x, y, oMachine1Beam)
fx.rotdir = rotdir
fx.image_angle = 90
fx = instance_create(x, y, oMachine1Beam)
fx.rotdir = rotdir
fx.image_angle = 180
fx = instance_create(x, y, oMachine1Beam)
fx.rotdir = rotdir
fx.image_angle = 270
