state = 0
statetime = 0
collectable = 0
reform = random(1)
move = 0
image_speed = 0.2
xvariant = 0
xtype = 1477
flashing = 0
fxtimer = 0
sizeX = 1
sizeY = 1
relativeX = 0
relativeY = 0
originVelX = 0
originVelY = 0
velX = 0
velY = 0
counter = 30
orbitX = xstart
orbitY = ystart
orbitCounter = 0
xExit = choose(-5, 5, -7, 7, -9, 9)
yExit = choose(-5, 5, -7, 7, -9, 9)
frozenAngle = 0
drawAngle = 0
drawHalzynShields = 0
inview = 1
