if (item == 0)
    myitem = instance_create(x, y, oItemBomb)
if (item == 10)
    myitem = instance_create(x, y, oItemCBeam)
if (item == 11)
    myitem = instance_create(x, y, oItemIBeam)
if (item == 4)
    myitem = instance_create(x, y, oItemHijump)
if (item == 5)
    myitem = instance_create(x, y, oItemVaria)
if (item == 12)
    myitem = instance_create(x, y, oItemWBeam)
if (item == 7)
    myitem = instance_create(x, y, oItemSpeedBooster)
if (item == 13)
    myitem = instance_create(x, y, oItemSBeam)
if (item == 6)
    myitem = instance_create(x, y, oItemSpaceJump)
if (item == 8)
    myitem = instance_create(x, y, oItemScrewAttack)
if (item == 14)
    myitem = instance_create(x, y, oItemPBeam)
if (item == 9)
    myitem = instance_create(x, y, oItemGravity)
if (item == 2)
    myitem = instance_create(x, y, oItemSpiderBall)
if (item == 3)
    myitem = instance_create(x, y, oItemJumpBall)
if (item == 52)
    myitem = instance_create(x, y, oItemM_52)
if (item == 53)
    myitem = instance_create(x, y, oItemM_53)
if (item == 54)
    myitem = instance_create(x, y, oItemM_54)
if (item == 55)
    myitem = instance_create(x, y, oItemM_55)
if (item == 56)
    myitem = instance_create(x, y, oItemM_56)
if (item == 57)
    myitem = instance_create(x, y, oItemM_57)
if (item == 60)
    myitem = instance_create(x, y, oItemM_60)
if (item == 100)
    myitem = instance_create(x, y, oItemM_100)
if (item == 101)
    myitem = instance_create(x, y, oItemM_101)
if (item == 102)
    myitem = instance_create(x, y, oItemM_102)
if (item == 104)
    myitem = instance_create(x, y, oItemM_104)
if (item == 105)
    myitem = instance_create(x, y, oItemM_105)
if (item == 106)
    myitem = instance_create(x, y, oItemM_106)
if (item == 107)
    myitem = instance_create(x, y, oItemM_107)
if (item == 109)
    myitem = instance_create(x, y, oItemM_109)
if (item == 111)
    myitem = instance_create(x, y, oItemM_111)
if (item == 150)
    myitem = instance_create(x, y, oItemM_150)
if (item == 151)
    myitem = instance_create(x, y, oItemM_151)
if (item == 152)
    myitem = instance_create(x, y, oItemM_152)
if (item == 153)
    myitem = instance_create(x, y, oItemM_153)
if (item == 154)
    myitem = instance_create(x, y, oItemM_154)
if (item == 155)
    myitem = instance_create(x, y, oItemM_155)
if (item == 156)
    myitem = instance_create(x, y, oItemM_156)
if (item == 159)
    myitem = instance_create(x, y, oItemM_159)
if (item == 161)
    myitem = instance_create(x, y, oItemM_161)
if (item == 163)
    myitem = instance_create(x, y, oItemM_163)
if (item == 202)
    myitem = instance_create(x, y, oItemM_202)
if (item == 203)
    myitem = instance_create(x, y, oItemM_203)
if (item == 204)
    myitem = instance_create(x, y, oItemM_204)
if (item == 205)
    myitem = instance_create(x, y, oItemM_205)
if (item == 208)
    myitem = instance_create(x, y, oItemM_208)
if (item == 210)
    myitem = instance_create(x, y, oItemM_210)
if (item == 211)
    myitem = instance_create(x, y, oItemM_211)
if (item == 214)
    myitem = instance_create(x, y, oItemM_214)
if (item == 250)
    myitem = instance_create(x, y, oItemM_250)
if (item == 252)
    myitem = instance_create(x, y, oItemM_252)
if (item == 255)
    myitem = instance_create(x, y, oItemM_255)
if (item == 257)
    myitem = instance_create(x, y, oItemM_257)
if (item == 259)
    myitem = instance_create(x, y, oItemM_259)
if (item == 303)
    myitem = instance_create(x, y, oItemM_303)
if (item == 304)
    myitem = instance_create(x, y, oItemM_304)
if (item == 307)
    myitem = instance_create(x, y, oItemM_307)
if (item == 308)
    myitem = instance_create(x, y, oItemM_308)
if (item == 309)
    myitem = instance_create(x, y, oItemM_309)
if (item == 51)
    myitem = instance_create(x, y, oItemSM_51)
if (item == 110)
    myitem = instance_create(x, y, oItemSM_110)
if (item == 162)
    myitem = instance_create(x, y, oItemSM_162)
if (item == 206)
    myitem = instance_create(x, y, oItemSM_206)
if (item == 207)
    myitem = instance_create(x, y, oItemSM_207)
if (item == 209)
    myitem = instance_create(x, y, oItemSM_209)
if (item == 215)
    myitem = instance_create(x, y, oItemSM_215)
if (item == 256)
    myitem = instance_create(x, y, oItemSM_256)
if (item == 300)
    myitem = instance_create(x, y, oItemSM_300)
if (item == 305)
    myitem = instance_create(x, y, oItemSM_305)
if (item == 50)
    myitem = instance_create(x, y, oItemETank_50)
if (item == 103)
    myitem = instance_create(x, y, oItemETank_103)
if (item == 108)
    myitem = instance_create(x, y, oItemETank_108)
if (item == 157)
    myitem = instance_create(x, y, oItemETank_157)
if (item == 158)
    myitem = instance_create(x, y, oItemETank_158)
if (item == 200)
    myitem = instance_create(x, y, oItemETank_200)
if (item == 201)
    myitem = instance_create(x, y, oItemETank_201)
if (item == 251)
    myitem = instance_create(x, y, oItemETank_251)
if (item == 254)
    myitem = instance_create(x, y, oItemETank_254)
if (item == 306)
    myitem = instance_create(x, y, oItemETank_306)
if (item == 58)
    myitem = instance_create(x, y, oItemPB_58)
if (item == 59)
    myitem = instance_create(x, y, oItemPB_59)
if (item == 112)
    myitem = instance_create(x, y, oItemPB_112)
if (item == 160)
    myitem = instance_create(x, y, oItemPB_160)
if (item == 212)
    myitem = instance_create(x, y, oItemPB_212)
if (item == 213)
    myitem = instance_create(x, y, oItemPB_213)
if (item == 253)
    myitem = instance_create(x, y, oItemPB_253)
if (item == 258)
    myitem = instance_create(x, y, oItemPB_258)
if (item == 301)
    myitem = instance_create(x, y, oItemPB_301)
if (item == 302)
    myitem = instance_create(x, y, oItemPB_302)
ballfade = instance_create(x, y, oFXTrail)
ballfade.sprite_index = sprite_index
ballfade.fadespeed = 0.1
ballfade.depth = 10
ballfx = instance_create(x, y, oFXTrail)
ballfx.sprite_index = sItemBallFX
ballfx.alpha = 3
ballfx.fadespeed = 0.1
ballfx.additive = 1
ballfx.depth = -10
global.chozo_message_item_id = item
instance_destroy()
