var i;
lbl[0] = get_text("Logs", "Briefing")
txt[0, 0] = get_text("Logs", "Briefing_Text")
pic[0, 0] = 238
lbl[1] = get_text("Logs", "Planet")
txt[1, 0] = get_text("Logs", "Planet_Text")
pic[1, 0] = 239
lbl[3] = get_text("Logs", "Earthquakes")
txt[3, 0] = get_text("Logs", "Earthquakes_Text")
pic[3, 0] = 240
lbl[4] = get_text("Logs", "ResearchTeam")
txt[4, 0] = get_text("Logs", "ResearchTeam_Text")
txt[4, 1] = get_text("Logs", "ResearchTeam_Text2")
pic[4, 0] = 238
pic[4, 1] = 241
lbl[5] = get_text("Logs", "RescueTeam")
txt[5, 0] = get_text("Logs", "RescueTeam_Text")
txt[5, 1] = get_text("Logs", "RescueTeam_Text2")
pic[5, 0] = 238
pic[5, 1] = 242
lbl[6] = get_text("Logs", "Thoth")
txt[6, 0] = get_text("Logs", "Thoth_Text")
txt[6, 1] = get_text("Logs", "Thoth_Text2")
pic[6, 0] = 243
pic[6, 1] = 243
lbl[10] = get_text("Logs", "Monsters")
txt[10, 0] = get_text("Logs", "Monsters_Text")
pic[10, 0] = 244
lbl[11] = get_text("Logs", "Mutations")
txt[11, 0] = get_text("Logs", "Mutations_Text")
pic[11, 0] = 245
lbl[12] = get_text("Logs", "AlphaMonster")
txt[12, 0] = get_text("Logs", "AlphaMonster_Text")
pic[12, 0] = 246
lbl[13] = get_text("Logs", "GammaMonster")
txt[13, 0] = get_text("Logs", "GammaMonster_Text")
pic[13, 0] = 247
lbl[14] = get_text("Logs", "ZetaMonster")
txt[14, 0] = get_text("Logs", "ZetaMonster_Text")
pic[14, 0] = 248
lbl[15] = get_text("Logs", "OmegaMonster")
txt[15, 0] = get_text("Logs", "OmegaMonster_Text")
pic[15, 0] = 249
lbl[16] = get_text("Logs", "QueenMonster")
txt[16, 0] = get_text("Logs", "QueenMonster_Text")
pic[16, 0] = 250
lbl[20] = get_text("Logs", "Chozo")
txt[20, 0] = get_text("Logs", "Chozo_Text")
pic[20, 0] = 251
lbl[21] = get_text("Logs", "GoldenTemple")
txt[21, 0] = get_text("Logs", "GoldenTemple_Text")
pic[21, 0] = 252
lbl[22] = get_text("Logs", "BreedingGrounds")
txt[22, 0] = get_text("Logs", "BreedingGrounds_Text")
txt[22, 1] = get_text("Logs", "BreedingGrounds_Text")
pic[22, 0] = 253
pic[22, 1] = 253
lbl[23] = get_text("Logs", "HydroStation")
txt[23, 0] = get_text("Logs", "HydroStation_Text")
pic[23, 0] = 254
lbl[24] = get_text("Logs", "IndustrialComplex")
txt[24, 0] = get_text("Logs", "IndustrialComplex_Text")
pic[24, 0] = 255
lbl[25] = get_text("Logs", "MiningFacility")
txt[25, 0] = get_text("Logs", "MiningFacility_Text")
pic[25, 0] = 256
lbl[26] = get_text("Logs", "Tower")
txt[26, 0] = get_text("Logs", "Tower_Text")
txt[26, 1] = get_text("Logs", "Tower_Text2")
pic[26, 0] = 257
pic[26, 1] = 258
lbl[27] = get_text("Logs", "PowerPlant")
txt[27, 0] = get_text("Logs", "PowerPlant_Text")
pic[27, 0] = 259
lbl[28] = get_text("Logs", "PowerDistribution")
txt[28, 0] = get_text("Logs", "PowerDistribution_Text")
txt[28, 1] = get_text("Logs", "PowerDistribution_Text2")
pic[28, 0] = 260
pic[28, 1] = 261
lbl[40] = get_text("Logs", "OmegaNest")
txt[40, 0] = get_text("Logs", "OmegaNest_Text")
pic[40, 0] = 272
lbl[29] = get_text("Logs", "GeneticLabs")
txt[29, 0] = get_text("Logs", "GeneticLabs_Text")
pic[29, 0] = 262
lbl[30] = get_text("Logs", "NativeSpecies")
txt[30, 0] = get_text("Logs", "NativeSpecies_Text")
pic[30, 0] = 263
lbl[31] = ""
txt[31, 0] = ""
pic[31, 0] = 264
lbl[32] = get_text("Logs", "AncientGuardian")
txt[32, 0] = get_text("Logs", "AncientGuardian_Text")
pic[32, 0] = 265
lbl[33] = get_text("Logs", "Arachnus")
txt[33, 0] = get_text("Logs", "Arachnus_Text")
pic[33, 0] = 266
lbl[34] = get_text("Logs", "Torizo")
txt[34, 0] = get_text("Logs", "Torizo_Text")
pic[34, 0] = 267
lbl[35] = get_text("Logs", "Tester")
txt[35, 0] = get_text("Logs", "Tester_Text")
pic[35, 0] = 268
lbl[36] = get_text("Logs", "TankPrototype")
txt[36, 0] = get_text("Logs", "TankPrototype_Text")
pic[36, 0] = 269
lbl[37] = get_text("Logs", "Serris")
txt[37, 0] = get_text("Logs", "Serris_Text")
pic[37, 0] = 270
lbl[38] = get_text("Logs", "Genesis")
txt[38, 0] = get_text("Logs", "Genesis_Text")
pic[38, 0] = 271
lbl[41] = get_text("NewLogs", "Nuclei")
txt[41, 0] = get_text("NewLogs", "Nuclei_Text")
pic[41, 0] = 315
lbl[42] = get_text("NewLogs", "Adaptations")
txt[42, 0] = get_text("NewLogs", "Adaptations_Text")
pic[42, 0] = 316
lbl[43] = get_text("NewLogs", "Radioactivity")
txt[43, 0] = get_text("NewLogs", "Radioactivity_Text")
pic[43, 0] = 317
if (global.log[44] == 1)
    lbl[44] = get_text("NewLogs", "ChozoMessage")
else if (global.log[44] == 2)
    lbl[44] = get_text("NewLogs", "ChozoMessage2")
txt[44, 0] = ("ＷＥ ＨＡＶＥ ＲＥＬＥＡＳＥＤ ＴＨＥ ＭＥＴＲＯＩＤＳ#ＴＨＥＹ ＨＡＶＥ ＦＡＲ ＳＵＲＰＡＳＳＥＤ ＯＵＲ ＥＸＰＥＣＴＡＴＩＯＮＳ# #ＡＳ ＷＥＬＬ ＡＳ ＯＵＲ ＣＯＮＴＲＯＬ# #ＥＶＥＮ ＳＯ ＷＥ ＡＲＥ ＳＴＲＩＣＫＥＮ ＷＩＴＨ ＧＵＩＬＴ ＡＮＤ ＧＲＩＥＦ ＡＳ ＷＥ ＬＥＡＶＥ ＴＨＥＭ ＩＮ Ａ ＵＮＩＶＥＲＳＥ ＴＨＡＴ ＩＳ ＮＯＴ ＲＥＡＤＹ ＦＯＲ ＴＨＥＩＲ ＥＸＩＳＴＥＮＣＥ# #ＰＲＡＹ ＦＯＲ ＴＨＥＩＲ ＳＵＣＣＥＳＳ# #ＰＲＡＹ ＦＯＲ ＴＨＥ ＳＡＦＥＴＹ ＯＦ ＡＬＬ ＬＩＦＥ ＩＮ ＴＨＥ ＣＯＳＭＯＳ##" + get_text("NewLogs", "ChozoMessage_Text"))
txt[44, 1] = get_text("NewLogs", "ChozoMessage_Text2")
pic[44, 0] = 318
pic[44, 1] = 319
lbl[45] = get_text("NewLogs", "TrooperLogs")
txt[45, 0] = ""
for (i = 0; i <= 7; i++)
{
    if (global.trooperlog[i] != 0)
    {
        txt[45, 0] += get_text("NewLogs", ("TrooperLogs_Text" + string(global.trooperlog[i])))
        if (i != 7)
            txt[45, 0] += "#-~-~-~-~-~-~-~-~-~-~-~-~-~-~-##"
    }
}
pic[45, 0] = 320
cat[0] = get_text("LogsCategories", "Intel")
cat[1] = get_text("LogsCategories", "Monsters")
cat[2] = get_text("LogsCategories", "TheChozo")
cat[3] = get_text("LogsCategories", "Hostiles")
cat[4] = get_text("NewLogsCategories", "Federation")
