if surface_exists(oControl.screen_surface)
{
    draw_surface(oControl.screen_surface, (view_xview[0] - (oControl.widescreen_space / 2)), view_yview[0])
    draw_surface_ext(oControl.screen_surface, ((view_xview[0] - (oControl.widescreen_space / 2)) + 1), view_yview[0], 1, 1, 0, -1, (0.5 * image_alpha))
    draw_surface_ext(oControl.screen_surface, ((view_xview[0] - (oControl.widescreen_space / 2)) - 1), view_yview[0], 1, 1, 0, -1, (0.5 * image_alpha))
    draw_surface_ext(oControl.screen_surface, ((view_xview[0] - (oControl.widescreen_space / 2)) + 2), view_yview[0], 1, 1, 0, -1, (0.2 * image_alpha))
    draw_surface_ext(oControl.screen_surface, ((view_xview[0] - (oControl.widescreen_space / 2)) - 2), view_yview[0], 1, 1, 0, -1, (0.2 * image_alpha))
}
draw_set_color(c_black)
if (!fadeout)
    draw_set_alpha(0.8)
if fadeout
    draw_set_alpha((0.8 * image_alpha))
draw_rectangle((view_xview[0] - (oControl.widescreen_space / 2)), view_yview[0], ((view_xview[0] + 330) + (oControl.widescreen_space / 2)), (view_yview[0] + 250), false)
if (global.ssmode > 0)
    draw_background_tiled_ext(bg_SubScrScanlines, (view_xview[0] - (oControl.widescreen_space / 2)), view_yview[0], 1, 1, -1, (0.2 * image_alpha))
draw_background_ext(bg_SubScrFX, (view_xview[0] - (oControl.widescreen_space / 2)), view_yview[0], 1, 1, 0, -1, (0.8 * image_alpha))
draw_background_ext(bg_SubScrFX, ((view_xview[0] + 320) + (oControl.widescreen_space / 2)), view_yview[0], -1, 1, 0, -1, (0.8 * image_alpha))
draw_background_ext(bg_SubScrFX, (view_xview[0] - (oControl.widescreen_space / 2)), (view_yview[0] + 240), 1, -1, 0, -1, (0.8 * image_alpha))
draw_background_ext(bg_SubScrFX, ((view_xview[0] + 320) + (oControl.widescreen_space / 2)), (view_yview[0] + 240), -1, -1, 0, -1, (0.8 * image_alpha))
