draw_set_alpha(argument6)
draw_set_color(argument3)
draw_text_transformed((argument0 + 1), argument1, argument2, argument7, argument7, image_angle)
draw_text_transformed((argument0 - 1), argument1, argument2, argument7, argument7, image_angle)
draw_text_transformed(argument0, (argument1 + 1), argument2, argument7, argument7, image_angle)
draw_text_transformed(argument0, (argument1 - 1), argument2, argument7, argument7, image_angle)
draw_text_transformed((argument0 + 1), (argument1 + 1), argument2, argument7, argument7, image_angle)
draw_text_transformed((argument0 + 1), (argument1 - 1), argument2, argument7, argument7, image_angle)
draw_text_transformed((argument0 - 1), (argument1 + 1), argument2, argument7, argument7, image_angle)
draw_text_transformed((argument0 - 1), (argument1 - 1), argument2, argument7, argument7, image_angle)
draw_text_transformed_colour(argument0, argument1, argument2, argument7, argument7, image_angle, argument4, argument4, argument5, argument5, argument6)
draw_set_alpha(1)
