canbeX = 1
CollisionBottom = 0
CollisionTop = 0
CollisionLeft = 0
CollisionRight = 0
i = 0
gravity = 0
gravity_direction = 270
state = 0
statetime = 0
myhealth = 3
facing = 1
hitcount = 0
xspeed = 0
angle = 0
rotspeed = 0
turning = 0
damage = global.mod_arachnusdamage
alarm[0] = 10
canbehit = 0
flashing = 0
fxtimer = 0
angry = 0
rolltime = 0
shaking = 0
shakeoffset = 0
spike_L1 = instance_create(20, 32, oArachnusSpikes)
spike_L1.facing = 1
spike_L1.targetx = 40
spike_L2 = instance_create(10, 64, oArachnusSpikes)
spike_L2.facing = 1
spike_L2.targetx = 40
spike_L3 = instance_create(0, 96, oArachnusSpikes)
spike_L3.facing = 1
spike_L3.targetx = 40
spike_R1 = instance_create(300, 32, oArachnusSpikes)
spike_R1.facing = -1
spike_R1.targetx = 280
spike_R2 = instance_create(310, 64, oArachnusSpikes)
spike_R2.facing = -1
spike_R2.targetx = 280
spike_R3 = instance_create(320, 96, oArachnusSpikes)
spike_R3.facing = -1
spike_R3.targetx = 280
state = 5
image_index = 0
sprite_index = sArachnusUnmorph
event_user(1)
PowerBombImmune = 0
dead = 0
