text1 = get_text("IntroCutscene", "Scene1")
text2 = get_text("IntroCutscene", "Scene2")
text3 = get_text("IntroCutscene", "Scene3")
drawtext = text1
state = 0
statetime = 0
textpos = 1
textalpha = 1
texty = 164
imgalpha = 0
drawimg = 158
