lockx = 0
locky = 0
snapx = 1
snapy = 1
targetx = oCharacter.x
targety = (oCharacter.y - 12)
ratiox = 1
ratioy = 1
focus = 0
focustime = 0
smoothin = 30
smoothout = 30
roomstart = 0
limit = (floor((oControl.widescreen_space / 2)) + 160)
