var zeta_list, zeta_sprites;
global.zeta_heads = ds_map_create()
zeta_list = ds_list_create()
ds_list_add(zeta_list, 191, 198, 213, 257)
zeta_sprites = ds_list_create()
ds_list_add(zeta_sprites, 590, 1625, 1627, 1629, 1633)
ds_list_shuffle(zeta_sprites)
for (i = 0; i < ds_list_size(zeta_list); i += 1)
    ds_map_add(global.zeta_heads, ds_list_find_value(zeta_list, i), ds_list_find_value(zeta_sprites, i))
if (irandom(99) < 3)
    ds_map_replace(global.zeta_heads, ds_list_find_value(zeta_list, irandom((ds_list_size(zeta_list) - 1))), 1631)
ds_list_destroy(zeta_list)
ds_list_destroy(zeta_sprites)
