image_speed = 0
open = 0
block = instance_create((x - 8), y, oSolid1)
block.image_yscale = 4
alarm[0] = 1
lock = 0
lockdelay = 0
showlock = 1
lockspr = 173
event = -1
highlight = 0
hltimer = 0
hlalpha = 0
stayopen = 0
alarm[2] = 10
