event_inherited()
beam = get_text("ItemsMenu", "Beams")
cbeam = get_text("ItemsMenu", "ChargeBeam")
ibeam = get_text("ItemsMenu", "IceBeam")
wbeam = get_text("ItemsMenu", "WaveBeam")
sbeam = get_text("ItemsMenu", "SpazerBeam")
pbeam = get_text("ItemsMenu", "PlasmaBeam")
