with (op[1])
    instance_destroy()
with (op[2])
    instance_destroy()
with (op[3])
    instance_destroy()
with (op[4])
    instance_destroy()
with (op[5])
    instance_destroy()
with (op[6])
    instance_destroy()
with (op[7])
    instance_destroy()
with (op[8])
    instance_destroy()
with (op[9])
    instance_destroy()
with (op[10])
    instance_destroy()
with (op[11])
    instance_destroy()
with (op[12])
    instance_destroy()
with (op[13])
    instance_destroy()
with (op[14])
    instance_destroy()
with (op[15])
    instance_destroy()
with (op[16])
    instance_destroy()
with (op[17])
    instance_destroy()
with (op[18])
    instance_destroy()
with (op[19])
    instance_destroy()
with (op[20])
    instance_destroy()
with (op[21])
    instance_destroy()
with (op[22])
    instance_destroy()
with (op[50])
    instance_destroy()
