scale = random_range(0.2, 1)
image_xscale = scale
image_yscale = scale
image_alpha = 0
max_alpha = (0.5 + random(0.5))
fadeout = 0
alarm[0] = (10 + random(300))
direction = random(360)
speed = random(0.5)
