if (audio_is_playing(musTitle) && currentbgm != 254)
    audio_stop_sound(musTitle)
if (audio_is_playing(musMainCave) && currentbgm != 257)
    audio_stop_sound(musMainCave)
if (audio_is_playing(musMonsterAppear) && currentbgm != 258)
    audio_stop_sound(musMonsterAppear)
if (audio_is_playing(musAlphaFight) && currentbgm != 259)
    audio_stop_sound(musAlphaFight)
if (audio_is_playing(musCaveAmbience) && currentbgm != 260)
    audio_stop_sound(musCaveAmbience)
if (audio_is_playing(musArea1A) && currentbgm != 261)
    audio_stop_sound(musArea1A)
if (audio_is_playing(musArea1B) && currentbgm != 262)
    audio_stop_sound(musArea1B)
if (audio_is_playing(musTester) && currentbgm != 369)
    audio_stop_sound(musTester)
if (audio_is_playing(musAncientGuardian) && currentbgm != 263)
    audio_stop_sound(musAncientGuardian)
if (audio_is_playing(musArea2A) && currentbgm != 265)
    audio_stop_sound(musArea2A)
if (audio_is_playing(musArea2B) && currentbgm != 266)
    audio_stop_sound(musArea2B)
if (audio_is_playing(musArachnus) && currentbgm != 267)
    audio_stop_sound(musArachnus)
if (audio_is_playing(musArea3A) && currentbgm != 268)
    audio_stop_sound(musArea3A)
if (audio_is_playing(musArea3B) && currentbgm != 269)
    audio_stop_sound(musArea3B)
if (audio_is_playing(musTorizoA) && currentbgm != 270)
    audio_stop_sound(musTorizoA)
if (audio_is_playing(musTorizoB) && currentbgm != 271)
    audio_stop_sound(musTorizoB)
if (audio_is_playing(musGammaFight) && currentbgm != 272)
    audio_stop_sound(musGammaFight)
if (audio_is_playing(musMainCave2) && currentbgm != 273)
    audio_stop_sound(musMainCave2)
if (audio_is_playing(musLabAmbience) && currentbgm != 274)
    audio_stop_sound(musLabAmbience)
if (audio_is_playing(musCaveAmbienceA4) && currentbgm != 275)
    audio_stop_sound(musCaveAmbienceA4)
if (audio_is_playing(musArea4A) && currentbgm != 276)
    audio_stop_sound(musArea4A)
if (audio_is_playing(musArea4B) && currentbgm != 277)
    audio_stop_sound(musArea4B)
if (audio_is_playing(musReactor) && currentbgm != 278)
    audio_stop_sound(musReactor)
if (audio_is_playing(musZetaFight) && currentbgm != 279)
    audio_stop_sound(musZetaFight)
if (audio_is_playing(musArea5A) && currentbgm != 280)
    audio_stop_sound(musArea5A)
if (audio_is_playing(musArea5B) && currentbgm != 281)
    audio_stop_sound(musArea5B)
if (audio_is_playing(musEris) && currentbgm != 282)
    audio_stop_sound(musEris)
if (audio_is_playing(musItemAmb) && currentbgm != 283)
    audio_stop_sound(musItemAmb)
if file_exists("musItemAmb2.ogg")
{
    if (audio_is_playing(musItemAmb2) && currentbgm != 348)
        audio_stop_sound(musItemAmb2)
}
