label = ""
logid = 0
newlog = 0
optionid = 0
alarm[0] = 1
tarea_x1 = 0
tarea_y1 = (y - 4)
tarea_x2 = 160
tarea_y2 = (y + 11)
t_x = 0
t_y = 0
t_click = 0
widescreen = oControl.widescreen
widescreen_space = oControl.widescreen_space
