tip1text = get_text("Title", "Tip1")
tip2text = get_text("Title", "Tip2")
op[4].label = get_text("Title", "Options")
op[5].label = get_text("Title", "Gallery")
op[6].label = get_text("Title", "Credits")
op[3].label = get_text("GameplayMenu", "Gameplay")
op[7].label = get_text("Title", "Exit")
