op[50].text = get_text("OptionsDisplay", "Title_Display")
op[0].label = get_text("OptionsDisplay", "Fullscreen")
if (os_type == os_android)
    op[0].label = get_text("OptionsDisplay", "VSync")
if global.opfullscreen
    op[1].label = get_text("OptionsDisplay", "DisplayScale")
else
    op[1].label = get_text("OptionsDisplay", "WindowSize")
op[2].label = get_text("OptionsDisplay", "VSync")
op[51].text = get_text("OptionsDisplay", "Title_HUD")
op[3].label = get_text("OptionsDisplay", "HUDDisplay")
op[4].label = get_text("OptionsDisplay", "HUDMap")
op[5].label = get_text("OptionsDisplay", "MonsterCounter")
op[52].text = get_text("OptionsDisplay", "Title_Notifications")
op[6].label = get_text("OptionsDisplay", "Hints")
op[7].label = get_text("ExtrasMenu", "Controller")
op[8].label = get_text("OptionsDisplay", "ScanNotifications")
op[9].label = get_text("OptionsDisplay", "Language")
op[10].label = get_text("Misc", "SensitivityMode")
op[11].label = get_text("Misc", "Widescreen")
op[12].label = get_text("GlobalOptions", "Exit")
with (oSS_Fg)
{
    opt_text1 = get_text("Subscreen", "Title_Options")
    tip1text = get_text("Subscreen", "Menu_Tip")
}
