display_set_gui_size(320, 240)
draw_set_alpha(image_alpha)
draw_set_font(global.fontGUI2)
draw_set_color(c_black)
draw_text(((x + 1) - widespace), (y + 17), text)
draw_set_color(c_white)
draw_text((x - widespace), (y + 16), text)
draw_set_alpha(1)
draw_set_color(c_black)
draw_rectangle((0 - widespace), 0, (330 + widespace), (120 - yoffset), false)
draw_rectangle((0 - widespace), (120 + yoffset), (330 + widespace), 250, false)
