with (front_obj)
    instance_destroy()
with (leg1f_obj)
    instance_destroy()
with (leg2f_obj)
    instance_destroy()
with (leg1b_obj)
    instance_destroy()
with (leg2b_obj)
    instance_destroy()
