instance_create(x, y, oTorizoGhost)
instance_destroy()
mytrail = instance_create((x - 4), y, oFXTrail)
mytrail.sprite_index = sTorizoEggPart1
mytrail.image_alpha = 1
mytrail.fadespeed = 0.05
mytrail.additive = 0
mytrail.hspeed = (-1 - random(3))
mytrail.vspeed = (-1 + random(2))
mytrail.gravity = 0.2
mytrail.gravity_direction = 270
mytrail.depth = -150
mytrail = instance_create((x + 4), y, oFXTrail)
mytrail.sprite_index = sTorizoEggPart1
mytrail.image_alpha = 1
mytrail.image_angle = 180
mytrail.fadespeed = 0.05
mytrail.additive = 0
mytrail.hspeed = (1 + random(3))
mytrail.vspeed = (-1 + random(2))
mytrail.gravity = 0.2
mytrail.gravity_direction = 270
mytrail.depth = -150
mytrail = instance_create(x, (y - 4), oFXTrail)
mytrail.sprite_index = sTorizoEggPart2
mytrail.image_alpha = 1
mytrail.fadespeed = 0.05
mytrail.additive = 0
mytrail.vspeed = (-1 + random(2))
mytrail.hspeed = (-2 - random(2))
mytrail.gravity = 0.2
mytrail.gravity_direction = 270
mytrail.depth = -150
mytrail = instance_create(x, (y + 4), oFXTrail)
mytrail.sprite_index = sTorizoEggPart2
mytrail.image_alpha = 1
mytrail.fadespeed = 0.05
mytrail.additive = 0
mytrail.vspeed = (-1 + random(2))
mytrail.hspeed = (2 + random(2))
mytrail.gravity = 0.2
mytrail.gravity_direction = 270
mytrail.depth = -150
