flash = instance_create(x, y, oFXTrail)
flash.sprite_index = sprite_index
flash.image_index = image_index
flash.image_alpha = 1
flash.white = 0
flash.fadespeed = 0.15
flash.depth = 10
flash.image_xscale = facing
flash.image_angle = image_angle
flash = instance_create((x + legfa1x), (y + legfa1y), oFXTrail)
flash.sprite_index = sMGammaLegFA1
flash.image_index = image_index
flash.image_alpha = 1
flash.white = 0
flash.fadespeed = 0.15
flash.depth = 10
flash.image_xscale = facing
flash.image_angle = (image_angle + legfa1da)
flash = instance_create(((x + legfa1x) + legfa2x), ((y + legfa1y) + legfa2y), oFXTrail)
flash.sprite_index = sMGammaLegFA2
flash.image_index = image_index
flash.image_alpha = 1
flash.white = 0
flash.fadespeed = 0.15
flash.depth = 10
flash.image_xscale = facing
flash.image_angle = ((image_angle + legfa1da) + legfa2da)
flash = instance_create((x + legfb1x), (y + legfb1y), oFXTrail)
flash.sprite_index = sMGammaLegFB1
flash.image_index = image_index
flash.image_alpha = 1
flash.white = 0
flash.fadespeed = 0.15
flash.depth = 10
flash.image_xscale = facing
flash.image_angle = (image_angle + legfb1da)
flash = instance_create(((x + legfb1x) + legfb2x), ((y + legfb1y) + legfb2y), oFXTrail)
flash.sprite_index = sMGammaLegFB2
flash.image_index = image_index
flash.image_alpha = 1
flash.white = 0
flash.fadespeed = 0.15
flash.depth = 10
flash.image_xscale = facing
flash.image_angle = ((image_angle + legfb1da) + legfb2da)
if (state == 5 || dodging)
    alarm[2] = 3
